### ISSUE TITLE
l2l.transforms.RandomRotation(degrees)

### ISSUE THREAD

**Issue by seba-1511** [seba-1511/learn2learn#20]
A vision transform that uniformly samples from iterable `degrees` the degress of rotation that will be applied to the image.

Example:

~~~python
rotate = l2l.transforms.RandomRotation([0.0, 90.0, 180.0, 270.0])
~~~

Question: should it be in `l2l.transforms` or `l2l.data.transforms` or `l2l.data.vision.transforms` ?

**Comment by praateekmahajan** [comment]
I am curious why if this is any different than [torchvision.transforms.RandomRotation](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomRotation)? Looks like we could use that.
